baseURL = 'https://spb.gofederation.ru/'
[languages]
  [languages.ru_RU]
    languageCode = 'ru'
    languageName = 'Русский'
    weight = 1
title = 'Го в Санкт-Петербурге'
disableKinds = ["rss", "taxonomy"]
[security]
  [security.funcs]
    getenv = ['^HUGO_']
